# Pandas数据结构

* 1.Series:一维数组
* 2.DataFrame:多维数组/表格
* 3.Index: 索引对象--不可变（immutable）

In [13]:
import pandas as pd

* Series

In [14]:
# 通过list构建Series
ser_obj = pd.Series(range(10, 20))
print(type(ser_obj))

<class 'pandas.core.series.Series'>


In [15]:
# 获取数据
print(ser_obj.values)

# 获取索引
print(type(ser_obj.index))

[10 11 12 13 14 15 16 17 18 19]
<class 'pandas.core.indexes.range.RangeIndex'>


In [16]:
# 预览数据
print(ser_obj.head())

0    10
1    11
2    12
3    13
4    14
dtype: int64


In [17]:
print(ser_obj)

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64


In [18]:
#通过索引获取数据
print(ser_obj[0])
print(ser_obj[8])

10
18


In [19]:
# 索引与数据的对应关系仍保持在数组运算的结果中
print(ser_obj * 2)
print(ser_obj[ser_obj > 15])

0    20
1    22
2    24
3    26
4    28
5    30
6    32
7    34
8    36
9    38
dtype: int64
6    16
7    17
8    18
9    19
dtype: int64


In [20]:
# 通过dict构建Series
year_data = {2001: 17.8, 2002: 20.1, 2003: 16.5}
ser_obj2 = pd.Series(year_data)
print(ser_obj2.head())
print(ser_obj2.index)

2001    17.8
2002    20.1
2003    16.5
dtype: float64
Int64Index([2001, 2002, 2003], dtype='int64')


In [21]:
# name属性
ser_obj2.name = 'temp'
ser_obj2.index.name = 'year'
print(ser_obj2.head())

year
2001    17.8
2002    20.1
2003    16.5
Name: temp, dtype: float64


* DataFrame

In [22]:
import numpy as np

# 通过ndarray构建DataFrame
array = np.random.randn(5,4)
print(array)

df_obj = pd.DataFrame(array)
print(df_obj.head())

[[-0.12980412  1.57584919 -0.30599626  1.23293662]
 [-0.36875619 -0.54241018 -0.00637239  1.48239652]
 [-0.54394821 -0.9364406  -0.32030949  1.77819459]
 [-1.71627871 -0.89612579 -0.07359301  0.01259354]
 [-0.61566577  1.49400383 -0.51759956 -0.32667468]]
          0         1         2         3
0 -0.129804  1.575849 -0.305996  1.232937
1 -0.368756 -0.542410 -0.006372  1.482397
2 -0.543948 -0.936441 -0.320309  1.778195
3 -1.716279 -0.896126 -0.073593  0.012594
4 -0.615666  1.494004 -0.517600 -0.326675


In [23]:
# 通过dict构建DataFrame
dict_data = {'A': 1., 
             'B': pd.Timestamp('20161217'),
             'C': pd.Series(1, index=list(range(4)),dtype='float32'),
             'D': np.array([3] * 4,dtype='int32'),
             'E' : pd.Categorical(["Python","Java","C++","C#"]),
             'F' : 'ChinaHadoop' }
#print dict_data
df_obj2 = pd.DataFrame(dict_data)
print(df_obj2.head())

     A          B    C  D       E            F
0  1.0 2016-12-17  1.0  3  Python  ChinaHadoop
1  1.0 2016-12-17  1.0  3    Java  ChinaHadoop
2  1.0 2016-12-17  1.0  3     C++  ChinaHadoop
3  1.0 2016-12-17  1.0  3      C#  ChinaHadoop


In [24]:
# 通过列索引获取列数据
print(df_obj2['A'])
print(type(df_obj2['A']))

print(df_obj2.A)

0    1.0
1    1.0
2    1.0
3    1.0
Name: A, dtype: float64
<class 'pandas.core.series.Series'>
0    1.0
1    1.0
2    1.0
3    1.0
Name: A, dtype: float64


In [25]:
# 增加列
df_obj2['G'] = df_obj2['D'] + 4
print(df_obj2.head())

     A          B    C  D       E            F  G
0  1.0 2016-12-17  1.0  3  Python  ChinaHadoop  7
1  1.0 2016-12-17  1.0  3    Java  ChinaHadoop  7
2  1.0 2016-12-17  1.0  3     C++  ChinaHadoop  7
3  1.0 2016-12-17  1.0  3      C#  ChinaHadoop  7


In [26]:
# 删除列
del(df_obj2['G'] )
print(df_obj2.head())

     A          B    C  D       E            F
0  1.0 2016-12-17  1.0  3  Python  ChinaHadoop
1  1.0 2016-12-17  1.0  3    Java  ChinaHadoop
2  1.0 2016-12-17  1.0  3     C++  ChinaHadoop
3  1.0 2016-12-17  1.0  3      C#  ChinaHadoop


* 索引对象 Index

In [27]:
print(type(ser_obj.index))
print(type(df_obj2.index))

print(df_obj2.index)

<class 'pandas.core.indexes.range.RangeIndex'>
<class 'pandas.core.indexes.numeric.Int64Index'>
Int64Index([0, 1, 2, 3], dtype='int64')


In [28]:
# 索引对象不可变
df_obj2.index[0] = 2

TypeError: Index does not support mutable operations