# Pandas数据结构

* 1.Series:一维数组
* 2.DataFrame:多维数组/表格
* 3.Index: 索引对象--不可变（immutable）

In [17]:
import pandas as pd
import numpy as np

* Series

In [2]:
# 通过list构建Series
ser_obj = pd.Series(range(10, 20))
print(type(ser_obj))

<class 'pandas.core.series.Series'>


In [3]:
# 获取数据
print(ser_obj.values)

# 获取索引
print(type(ser_obj.index))

[10 11 12 13 14 15 16 17 18 19]
<class 'pandas.core.indexes.range.RangeIndex'>


In [4]:
# 预览数据
print(ser_obj.head())

0    10
1    11
2    12
3    13
4    14
dtype: int64


In [5]:
print(ser_obj)

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64


In [6]:
#通过索引获取数据
print(ser_obj[0])
print(ser_obj[8])

10
18


In [7]:
# 索引与数据的对应关系仍保持在数组运算的结果中
print(ser_obj * 2)
print(ser_obj[ser_obj > 15])

0    20
1    22
2    24
3    26
4    28
5    30
6    32
7    34
8    36
9    38
dtype: int64
6    16
7    17
8    18
9    19
dtype: int64


In [8]:
# 通过dict构建Series
year_data = {2001: 17.8, 2002: 20.1, 2003: 16.5}
ser_obj2 = pd.Series(year_data)
print(ser_obj2.head())
print(ser_obj2.index)

2001    17.8
2002    20.1
2003    16.5
dtype: float64
Int64Index([2001, 2002, 2003], dtype='int64')


In [9]:
# name属性
ser_obj2.name = 'temp'
ser_obj2.index.name = 'year'
print(ser_obj2.head())

year
2001    17.8
2002    20.1
2003    16.5
Name: temp, dtype: float64


* DataFrame

In [10]:
# 通过ndarray构建DataFrame
array = np.random.randn(5,4)
print(array)

df_obj = pd.DataFrame(array)
print(df_obj.head())

[[ 0.00938373 -0.52942147 -1.5108186  -0.07417943]
 [-0.60189694 -0.58113841  1.61481741  0.12810457]
 [-0.02980562 -1.00109784  0.46345444  0.2658796 ]
 [-1.38939543 -1.20036896 -0.6162206  -0.50731035]
 [-0.01783735 -0.86139758  0.14783172  1.16689408]]
          0         1         2         3
0  0.009384 -0.529421 -1.510819 -0.074179
1 -0.601897 -0.581138  1.614817  0.128105
2 -0.029806 -1.001098  0.463454  0.265880
3 -1.389395 -1.200369 -0.616221 -0.507310
4 -0.017837 -0.861398  0.147832  1.166894


In [11]:
# 通过dict构建DataFrame
dict_data = {'A': 1., 
             'B': pd.Timestamp('20190701'),
             'C': pd.Series(1, index=list(range(4)),dtype='float32'),
             'D': np.array([3] * 4,dtype='int32'),
             'E' : pd.Categorical(["Python","Java","C++","C#"]),
             'F' : 'Pandas' }
#print dict_data
df_obj2 = pd.DataFrame(dict_data)
print(df_obj2.head())

     A          B    C  D       E       F
0  1.0 2019-07-01  1.0  3  Python  Pandas
1  1.0 2019-07-01  1.0  3    Java  Pandas
2  1.0 2019-07-01  1.0  3     C++  Pandas
3  1.0 2019-07-01  1.0  3      C#  Pandas


In [12]:
# 通过列索引获取列数据
print(df_obj2['A'])
print(type(df_obj2['A']))

print(df_obj2.A)

0    1.0
1    1.0
2    1.0
3    1.0
Name: A, dtype: float64
<class 'pandas.core.series.Series'>
0    1.0
1    1.0
2    1.0
3    1.0
Name: A, dtype: float64


In [13]:
# 增加列
df_obj2['G'] = df_obj2['D'] + 4
print(df_obj2.head())

     A          B    C  D       E       F  G
0  1.0 2019-07-01  1.0  3  Python  Pandas  7
1  1.0 2019-07-01  1.0  3    Java  Pandas  7
2  1.0 2019-07-01  1.0  3     C++  Pandas  7
3  1.0 2019-07-01  1.0  3      C#  Pandas  7


In [14]:
# 删除列
del(df_obj2['G'] )
print(df_obj2.head())

     A          B    C  D       E       F
0  1.0 2019-07-01  1.0  3  Python  Pandas
1  1.0 2019-07-01  1.0  3    Java  Pandas
2  1.0 2019-07-01  1.0  3     C++  Pandas
3  1.0 2019-07-01  1.0  3      C#  Pandas


* 索引对象 Index

In [15]:
print(type(ser_obj.index))
print(type(df_obj2.index))

print(df_obj2.index)

<class 'pandas.core.indexes.range.RangeIndex'>
<class 'pandas.core.indexes.numeric.Int64Index'>
Int64Index([0, 1, 2, 3], dtype='int64')


In [16]:
# 索引对象不可变
df_obj2.index[0] = 2

TypeError: Index does not support mutable operations