<a href="https://colab.research.google.com/github/SlimAnthony/Pandas_Experiments/blob/master/07_data_preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 数据准备 Data Preparation

1. data cleansing 

> 数据清理

2. data merge/concat 

> 数据连接与合并

3. reshape 

> 重构

4. transform 

> 转化








## 数据清理 cleansing



*   Duplicates
*   Missing data    > pd.fillna( ) , pd.dropna()   [处理缺失数据](https://pandas.pydata.org/pandas-docs/stable/user_guide/missing_data.html)
*   Inconsistant format 
*   Outliers



## 数据连接 merge

[Merge, join and concatenate](https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html#merging)

* pd.merge (
    left,
    right,
    
    how='inner',
    
    on=None,
    left_on=None,
    right_on=None,
    
    left_index=False,
    right_index=False,
    
    suffixes=('_x', '_y'),
    
    sort=False,
    copy=True,
    indicator=False,
    validate=None,
    )

根据单个或多个键将不同 Data Frame 的行连接起来 , 类比数据库的连接操作

* 默 认 将 重 叠 列 的 列 名 作 为 " 外 键 " 进 行 连 接

> on ，显 示 指 定 " 外 键 "

> left_on ， 左 侧 数 据 的 " 外 键 "   

> right_on ， 右 侧 数 据 的 " 外 键 ' 


* how: 指定连接方式。默 认 是 " 内 连 接 " (inner) ， 即 结 果 中 的 键 是 交 集

      use intersection of keys from both frames, similar to a SQL inner join; preserve the order of the left keys.

> outer: 并集

      use union of keys from both frames, similar to a SQL full outer join; sort keys lexicographically.


> Left/Right





In [0]:
import pandas as pd
import numpy as np

In [51]:
df_obj1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                        'data1' : np.random.randint(0,10,7)})
df_obj2 = pd.DataFrame({'key': ['a', 'b', 'd'],
                        'data2' : [5,6,7]})

print(df_obj1)
print(df_obj2)

  key  data1
0   b      6
1   b      8
2   a      6
3   c      8
4   a      1
5   a      5
6   b      3
  key  data2
0   a      5
1   b      6
2   d      7


In [52]:
# 默认将重叠列的列名作为“外键”进行连接
pd.merge(df_obj1, df_obj2)

key  data1  data2
0   b      6      6
1   b      8      6
2   b      3      6
3   a      6      5
4   a      1      5
5   a      5      5

In [53]:
# on显示指定“外键”
pd.merge(df_obj1, df_obj2, on='key')

key  data1  data2
0   b      6      6
1   b      8      6
2   b      3      6
3   a      6      5
4   a      1      5
5   a      5      5

In [0]:
# left_on，right_on分别指定左侧数据和右侧数据的“外键”

# 更改列名
df_obj1 = df_obj1.rename(columns={'key':'key1'})
df_obj2 = df_obj2.rename(columns={'key':'key2'})

In [55]:
pd.merge(df_obj1, df_obj2, left_on='key1', right_on='key2')

key1  data1 key2  data2
0    b      6    b      6
1    b      8    b      6
2    b      3    b      6
3    a      6    a      5
4    a      1    a      5
5    a      5    a      5

In [56]:
# “外连接”
pd.merge(df_obj1, df_obj2, left_on='key1', right_on='key2', how='outer')

key1  data1 key2  data2
0    b    6.0    b    6.0
1    b    8.0    b    6.0
2    b    3.0    b    6.0
3    a    6.0    a    5.0
4    a    1.0    a    5.0
5    a    5.0    a    5.0
6    c    8.0  NaN    NaN
7  NaN    NaN    d    7.0

In [57]:
# 左连接 left : use only keys from left frame, similar to a SQL left outer join;  preserve key order.
pd.merge(df_obj1, df_obj2, left_on='key1', right_on='key2', how='left')

key1  data1 key2  data2
0    b      6    b    6.0
1    b      8    b    6.0
2    a      6    a    5.0
3    c      8  NaN    NaN
4    a      1    a    5.0
5    a      5    a    5.0
6    b      3    b    6.0

In [58]:
# 右连接 right: use only keys from right frame, similar to a SQL right outer join;preserve key order.      
pd.merge(df_obj1, df_obj2, left_on='key1', right_on='key2', how='right')

key1  data1 key2  data2
0    b    6.0    b      6
1    b    8.0    b      6
2    b    3.0    b      6
3    a    6.0    a      5
4    a    1.0    a      5
5    a    5.0    a      5
6  NaN    NaN    d      7

In [59]:
# 处理重复列名
df_obj1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                        'data' : np.random.randint(0,10,7)})
df_obj2 = pd.DataFrame({'key': ['a', 'b', 'd'],
                        'data' : np.random.randint(0,10,3)})

pd.merge(df_obj1, df_obj2, on='key', suffixes=('_left', '_right'))

key  data_left  data_right
0   b          9           8
1   b          9           8
2   b          7           8
3   a          6           5
4   a          9           5
5   a          8           5

In [0]:
# 按索引连接
df_obj1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                        'data1' : np.random.randint(0,10,7)})
df_obj2 = pd.DataFrame({'data2' : np.random.randint(0,10,3)}, index=['a', 'b', 'd'])

In [61]:
pd.merge(df_obj1, df_obj2, left_on='key', right_index=True)

key  data1  data2
0   b      9      0
1   b      9      0
6   b      3      0
2   a      6      2
4   a      0      2
5   a      8      2

![SQL Joins](Images/pandas_join.png)


## 数据合并 concat

* pd.concat
沿轴方向将多个对象合并到一起

* 注意指定轴方向，默认axis=0    
   {0/'index', 1/'columns'}

* Join指定合并方式默认为outer

* Series合并时查看行索引
   DataFrame合并时同时看行索引和列索引

* NumPy的concat

> np.concatenate



In [62]:
arr1 = np.random.randint(0, 10, (3, 4))
arr2 = np.random.randint(0, 10, (3, 4))

print(arr1)
print(arr2)

[[8 0 5 9]
 [3 7 0 0]
 [4 5 7 6]]
[[6 9 8 7]
 [2 3 6 9]
 [2 5 0 3]]


In [63]:
np.concatenate([arr1, arr2])

array([[8, 0, 5, 9],
       [3, 7, 0, 0],
       [4, 5, 7, 6],
       [6, 9, 8, 7],
       [2, 3, 6, 9],
       [2, 5, 0, 3]])

In [64]:
np.concatenate([arr1, arr2], axis=1)

array([[8, 0, 5, 9, 6, 9, 8, 7],
       [3, 7, 0, 0, 2, 3, 6, 9],
       [4, 5, 7, 6, 2, 5, 0, 3]])

* Series上的concat

In [65]:
# index 没有重复的情况
ser_obj1 = pd.Series(np.random.randint(0, 10, 5), index=range(0,5))
ser_obj2 = pd.Series(np.random.randint(0, 10, 4), index=range(5,9))
ser_obj3 = pd.Series(np.random.randint(0, 10, 3), index=range(9,12))

print(ser_obj1)
print(ser_obj2)
print(ser_obj3)

0    7
1    0
2    0
3    8
4    1
dtype: int64
5    4
6    0
7    6
8    6
dtype: int64
9     9
10    5
11    3
dtype: int64


In [66]:
pd.concat([ser_obj1, ser_obj2, ser_obj3])

0     7
1     0
2     0
3     8
4     1
5     4
6     0
7     6
8     6
9     9
10    5
11    3
dtype: int64

In [67]:
pd.concat([ser_obj1, ser_obj2, ser_obj3], axis=1)

0    1    2
0   7.0  NaN  NaN
1   0.0  NaN  NaN
2   0.0  NaN  NaN
3   8.0  NaN  NaN
4   1.0  NaN  NaN
5   NaN  4.0  NaN
6   NaN  0.0  NaN
7   NaN  6.0  NaN
8   NaN  6.0  NaN
9   NaN  NaN  9.0
10  NaN  NaN  5.0
11  NaN  NaN  3.0

In [68]:
# index 有重复的情况
ser_obj1 = pd.Series(np.random.randint(0, 10, 5), index=range(5))
ser_obj2 = pd.Series(np.random.randint(0, 10, 4), index=range(4))
ser_obj3 = pd.Series(np.random.randint(0, 10, 3), index=range(3))

pd.concat([ser_obj1, ser_obj2, ser_obj3])

0    4
1    5
2    4
3    7
4    1
0    1
1    7
2    1
3    2
0    4
1    5
2    5
dtype: int64

In [69]:
pd.concat([ser_obj1, ser_obj2, ser_obj3], axis=1, join='inner')

0  1  2
0  4  1  4
1  5  7  5
2  4  1  5

* DataFrame上的concat

In [70]:
df_obj1 = pd.DataFrame(np.random.randint(0, 10, (3, 2)), index=['a', 'b', 'c'],
                       columns=['A', 'B'])
df_obj2 = pd.DataFrame(np.random.randint(0, 10, (2, 2)), index=['a', 'b'],
                       columns=['C', 'D'])
print(df_obj1)
print(df_obj2)

   A  B
a  8  9
b  8  8
c  9  1
   C  D
a  9  2
b  4  7


In [71]:
pd.concat([df_obj1, df_obj2],sort=True)

A    B    C    D
a  8.0  9.0  NaN  NaN
b  8.0  8.0  NaN  NaN
c  9.0  1.0  NaN  NaN
a  NaN  NaN  9.0  2.0
b  NaN  NaN  4.0  7.0

In [72]:
pd.concat([df_obj1, df_obj2],axis=1,sort=True)

A  B    C    D
a  8  9  9.0  2.0
b  8  8  4.0  7.0
c  9  1  NaN  NaN

## 数据重构 Reshape 

> Stack/unstack   

[Hierarchical Indexing层级索引](https://pandas.pydata.org/pandas-docs/stable/user_guide/advanced.html#advanced-hierarchical)

[Reshaping](https://pandas.pydata.org/pandas-docs/stable/user_guide/reshaping.html#reshaping-stacking)



* stack 

The stack() method “compresses” a level in the DataFrame’s columns.

In [73]:
df_obj = pd.DataFrame(np.random.randint(0,10, (5,2)), columns=['data1', 'data2'])
df_obj

data1  data2
0      9      6
1      3      7
2      7      8
3      5      2
4      9      1

In [74]:
#将列索引旋转为行索引，完成层级索引， DataFrame->Series
stacked = df_obj.stack()
print(stacked)

print(type(stacked))
print(type(stacked.index))

0  data1    9
   data2    6
1  data1    3
   data2    7
2  data1    7
   data2    8
3  data1    5
   data2    2
4  data1    9
   data2    1
dtype: int64
<class 'pandas.core.series.Series'>
<class 'pandas.core.indexes.multi.MultiIndex'>


In [75]:
#unstack
#将层级索引展开 Series->DataFrame
#默认操作内层索引，即level=-l
stacked.unstack()

data1  data2
0      9      6
1      3      7
2      7      8
3      5      2
4      9      1

In [76]:
# 通过level指定操作索引的级别
stacked.unstack(level=0)

0  1  2  3  4
data1  9  3  7  5  9
data2  6  7  8  2  1

## 数据转换 Transform

> 处理重复数据

> map

> 数据替换 replace


* 处理重复数据

In [77]:
df_obj = pd.DataFrame({'data1' : ['a'] * 4 + ['b'] * 4,
                       'data2' : np.random.randint(0, 4, 8)})
df_obj

data1  data2
0     a      2
1     a      0
2     a      0
3     a      3
4     b      2
5     b      0
6     b      1
7     b      1

In [78]:
df_obj.duplicated() # duplicated()返回布尔型Series表示每行是否为重复行

0    False
1    False
2     True
3    False
4    False
5    False
6    False
7     True
dtype: bool

In [79]:
df_obj.drop_duplicates() # dropduplicates()过滤重复行

data1  data2
0     a      2
1     a      0
3     a      3
4     b      2
5     b      0
6     b      1

In [80]:
df_obj.drop_duplicates('data2') #默认判断全部列,可指定按某些列判断

data1  data2
0     a      2
1     a      0
3     a      3
6     b      1

* map函数

   Series根据map传入的函数对每行或每列进行转换

In [86]:
df = pd.Series(np.random.randint(0,10,10))
df

0    6
1    0
2    4
3    3
4    0
5    5
6    8
7    9
8    1
9    3
dtype: int64

In [87]:
df.map(lambda x : x ** 2)

0    36
1     0
2    16
3     9
4     0
5    25
6    64
7    81
8     1
9     9
dtype: int64

* 数据替换 replace

In [88]:
# 替换单个值
df.replace(0, -1)

0    6
1   -1
2    4
3    3
4   -1
5    5
6    8
7    9
8    1
9    3
dtype: int64

In [90]:
# 替换多个值
df.replace([0, 3], -10)

0     6
1   -10
2     4
3   -10
4   -10
5     5
6     8
7     9
8     1
9   -10
dtype: int64

In [91]:
df.replace([0,3],[-10,-20])

0     6
1   -10
2     4
3   -20
4   -10
5     5
6     8
7     9
8     1
9   -20
dtype: int64